comment: false
codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default: on
      validate:
        target: 100%
        flags:
          - validate
      repositories:
        target: 100%
        flags:
          - repositories

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "tests"
flags:
  validate:
    paths:
      - custom_components/hacs/validate/
  repositories:
    paths:
      - custom_components/hacs/repositories/