[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
profile = "black"
# will group `import x` and `from x import` of the same module.
force_sort_within_sections = true
known_first_party = [
    "custom_components",
    "tests",
]
forced_separate = [
    "tests",
]
combine_as_imports = true


[tool.pytest.ini_options]
asyncio_mode="auto"
addopts = "-rxf -l --cov=./ --cov-report=xml"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore:It is recommended to use web.AppKey instances for keys"
]
log_format = "%(asctime)s.%(msecs)03d %(levelname)-8s %(threadName)s %(name)s:%(filename)s:%(lineno)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
testpaths = [
    "tests",
]
python_files = [
    "test_*.py",
]

norecursedirs = [
    ".git",
]

[tool.ruff]
fix = true
line-length = 100
show-fixes = true
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
 "A002",
 "ANN001",
 "ANN002",
 "ANN003",
 "ANN101",
 "ANN201",
 "ANN202",
 "ANN204",
 "ANN205",
 "ANN401",
 "ARG001",
 "ARG002",
 "ARG005",
 "ASYNC230",
 "B904",
 "BLE001",
 "C901",
 "COM812",
 "D100",
 "D101",
 "D102",
 "D103",
 "D104",
 "D105",
 "D107",
 "D202",
 "D203",
 "D205",
 "D211",
 "D212",
 "D213",
 "D400",
 "D401",
 "D403",
 "D415",
 "DTZ003",
 "E501",
 "E712",
 "E713",
 "E741",
 "EM101",
 "EM102",
 "ERA001",
 "F401",
 "F541",
 "FBT001",
 "FBT002",
 "FBT003",
 "I001",
 "INP001",
 "ISC001",
 "N811",
 "N812",
 "N818",
 "PERF401",
 "PERF402",
 "PIE804",
 "PLC0414",
 "PLR0912",
 "PLR0913",
 "PLR0915",
 "PLR1714",
 "PLR1722",
 "PLR2004",
 "PLR5501",
 "PLW2901",
 "PT001",
 "PT004",
 "PT006",
 "PT007",
 "PT011",
 "PT014",
 "PT019",
 "PT022",
 "PTH103",
 "PTH107",
 "PTH109",
 "PTH110",
 "PTH113",
 "PTH118",
 "PTH120",
 "PTH123",
 "PTH207",
 "PYI030",
 "RET502",
 "RET503",
 "RET504",
 "RET505",
 "RET507",
 "RSE102",
 "RUF005",
 "RUF012",
 "RUF013",
 "RUF100",
 "S101",
 "S105",
 "S110",
 "SIM102",
 "SIM103",
 "SIM105",
 "SIM108",
 "SIM110",
 "SIM114",
 "SIM117",
 "SLF001",
 "T201",
 "TCH001",
 "TCH002",
 "TCH003",
 "TID252",
 "TRY002",
 "TRY003",
 "TRY201",
 "TRY300",
 "TRY301",
 "TRY400",
 "TRY401",
 "UP035",
 "UP038",
 "UP040",
 "YTT204"
]

fixable = ["ALL"]
unfixable = []


[tool.ruff.lint.isort]
combine-as-imports = true
force-sort-within-sections = true
known-first-party = [
  "custom_components.hacs",
]