[tool.black]
line-length = 100
target-version = ['py311']
exclude = 'generated'

[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
profile = "black"
# will group `import x` and `from x import` of the same module.
force_sort_within_sections = true
known_first_party = [
    "custom_components",
    "tests",
]
forced_separate = [
    "tests",
]
combine_as_imports = true


[tool.pytest.ini_options]
asyncio_mode="auto"
addopts = "-rxf -l --cov=./ --cov-report=xml"
filterwarnings = [
    "ignore::DeprecationWarning",
]
log_format = "%(asctime)s.%(msecs)03d %(levelname)-8s %(threadName)s %(name)s:%(filename)s:%(lineno)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
testpaths = [
    "tests",
]
python_files = [
    "test_*.py",
]

norecursedirs = [
    ".git",
]