name: "HACS"

on:
  push:
    branches: master 
  pull_request:
    labeles: backend

jobs:
  backend:
    name: Backend Test
    runs-on: ubuntu-latest
    steps:
      - uses: ludeeus/hacs-actions@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          action: "IssueGreeter"