name: Codecov

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run:
    #runs-on: ubuntu-latest
    container:
      image: ludeeus/container:python
    name: Codecov
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run:  make init

    - name: Generate coverage report
      env:
        PYTEST: true
      run: |
        pip install pytest
        pip install pytest-cov
        python3 -m pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}