name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  pytest:
    name: PyTest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    runs-on: ubuntu-latest
    steps:
    - name: "Get the repository content"
      uses: actions/checkout@v2

    - name: Enable version ${{ matrix.python-version }} of Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: make init

    - name: Run pytest
      run: python -m pytest