name: Testing

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test_frontend_build:
    name: Test frontend build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the HACS frontend
        run: |
          cd frontend
          npm install
          npm run build