name: Validate

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: validate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-hassfest:
    runs-on: ubuntu-latest
    name: With hassfest
    steps:
    - name: 📥 Checkout the repository
      uses: actions/checkout@v4.1.1

    - name: 🏃 Hassfest validation
      uses: "home-assistant/actions/hassfest@master"


  validate-hacs:
    runs-on: ubuntu-latest
    name: With HACS Action
    steps:
    - name: 🏃 HACS validation
      uses: hacs/action@main
      with:
        category: integration

  validate-hacs-local:
    runs-on: ubuntu-latest
    name: With HACS Action (local)
    if: ${{ github.event_name != 'schedule' }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.1

      - name: Build Container
        run: |
          cd action
          docker build . -t hacs/action:local

      - name: Run Action
        run: |
          docker run --name hacs_action_local \
            --env INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            --env INPUT_REPOSITORY=${{github.repository}} \
            --env INPUT_CATEGORY=integration \
            hacs/action:local


  validata-hacs-data:
    runs-on: ubuntu-latest
    name: Validate HACS data generation
    if: ${{ github.event_name != 'schedule' }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        id: python
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: |
            requirements_base.txt
            requirements_generate_data.txt

      - name: Install dependencies
        run:  |
          scripts/install/frontend
          scripts/install/pip_packages --requirement requirements_generate_data.txt

      - name: Generate data
        run: python3 -m scripts.data.generate_category_data integration hacs/integration
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate output with JQ
        run: |
          jq -c . outputdata/integration/data.json
          jq -c . outputdata/integration/repositories.json

  validate-homeassistant:
    name: With Home Assistant
    strategy:
      matrix:
        channel: [stable, beta, dev, "2023.6.0"]
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4.1.1

      - name: 📋 Copy sample configuration for Home Assistant
        run: |
          mkdir ./test_configuration
          bash scripts/install/frontend
          cp -r ./custom_components ./test_configuration
          echo "default_config:" >> ./test_configuration/configuration.yaml
          echo "hacs:" >> ./test_configuration/configuration.yaml
          echo "  token: CHANGE_ME" >> ./test_configuration/configuration.yaml

      - name: 🛠️ Setup Home Assistant
        id: homeassistant
        uses: ludeeus/setup-homeassistant@main
        with:
          tag: ${{ matrix.channel }}
          config-dir: test_configuration


  notify_on_failure:
    runs-on: ubuntu-latest
    name: Trigger Discord notification when jobs fail
    needs: ["validate-hassfest", "validate-hacs", "validate-homeassistant"]
    if: ${{ always() && contains(join(needs.*.result, ','), 'failure') && github.event_name == 'schedule' }}
    steps:
      - name: Send notification
        run: |
          curl \
            -H "Content-Type: application/json" \
            -d '{"username": "GitHub action failure", "content": "[Scheduled action failed!](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})"}' \
            ${{ secrets.DISCORD_WEBHOOK_ACTION_FAILURE }}